//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIAnalysisResult) DeepCopyInto(out *AIAnalysisResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIAnalysisResult.
func (in *AIAnalysisResult) DeepCopy() *AIAnalysisResult {
	if in == nil {
		return nil
	}
	out := new(AIAnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIConfig) DeepCopyInto(out *AIConfig) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIConfig.
func (in *AIConfig) DeepCopy() *AIConfig {
	if in == nil {
		return nil
	}
	out := new(AIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerError) DeepCopyInto(out *ContainerError) {
	*out = *in
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerError.
func (in *ContainerError) DeepCopy() *ContainerError {
	if in == nil {
		return nil
	}
	out := new(ContainerError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorPattern) DeepCopyInto(out *ErrorPattern) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorPattern.
func (in *ErrorPattern) DeepCopy() *ErrorPattern {
	if in == nil {
		return nil
	}
	out := new(ErrorPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAnalysisConfig) DeepCopyInto(out *LogAnalysisConfig) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CacheEnabled != nil {
		in, out := &in.CacheEnabled, &out.CacheEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CacheTTL != nil {
		in, out := &in.CacheTTL, &out.CacheTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LinesToAnalyze != nil {
		in, out := &in.LinesToAnalyze, &out.LinesToAnalyze
		*out = new(int32)
		**out = **in
	}
	if in.FilterErrorsOnly != nil {
		in, out := &in.FilterErrorsOnly, &out.FilterErrorsOnly
		*out = new(bool)
		**out = **in
	}
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]ErrorPattern, len(*in))
		copy(*out, *in)
	}
	if in.AIAPIKey != nil {
		in, out := &in.AIAPIKey, &out.AIAPIKey
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MethodConfigs != nil {
		in, out := &in.MethodConfigs, &out.MethodConfigs
		*out = make([]MethodConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAnalysisConfig.
func (in *LogAnalysisConfig) DeepCopy() *LogAnalysisConfig {
	if in == nil {
		return nil
	}
	out := new(LogAnalysisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogAnalysisResult) DeepCopyInto(out *LogAnalysisResult) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PatternResult != nil {
		in, out := &in.PatternResult, &out.PatternResult
		*out = new(PatternAnalysisResult)
		**out = **in
	}
	if in.AIResult != nil {
		in, out := &in.AIResult, &out.AIResult
		*out = new(AIAnalysisResult)
		**out = **in
	}
	if in.ErrorLines != nil {
		in, out := &in.ErrorLines, &out.ErrorLines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AnalyzedAt.DeepCopyInto(&out.AnalyzedAt)
	in.CachedAt.DeepCopyInto(&out.CachedAt)
	if in.CacheExpiresAt != nil {
		in, out := &in.CacheExpiresAt, &out.CacheExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogAnalysisResult.
func (in *LogAnalysisResult) DeepCopy() *LogAnalysisResult {
	if in == nil {
		return nil
	}
	out := new(LogAnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodConfig) DeepCopyInto(out *MethodConfig) {
	*out = *in
	if in.PatternConfig != nil {
		in, out := &in.PatternConfig, &out.PatternConfig
		*out = new(PatternConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AIConfig != nil {
		in, out := &in.AIConfig, &out.AIConfig
		*out = new(AIConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodConfig.
func (in *MethodConfig) DeepCopy() *MethodConfig {
	if in == nil {
		return nil
	}
	out := new(MethodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonReadyPodInfo) DeepCopyInto(out *NonReadyPodInfo) {
	*out = *in
	if in.ContainerErrors != nil {
		in, out := &in.ContainerErrors, &out.ContainerErrors
		*out = make([]ContainerError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodConditions != nil {
		in, out := &in.PodConditions, &out.PodConditions
		*out = make([]PodCondition, len(*in))
		copy(*out, *in)
	}
	if in.LogAnalysis != nil {
		in, out := &in.LogAnalysis, &out.LogAnalysis
		*out = new(LogAnalysisResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonReadyPodInfo.
func (in *NonReadyPodInfo) DeepCopy() *NonReadyPodInfo {
	if in == nil {
		return nil
	}
	out := new(NonReadyPodInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternAnalysisResult) DeepCopyInto(out *PatternAnalysisResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternAnalysisResult.
func (in *PatternAnalysisResult) DeepCopy() *PatternAnalysisResult {
	if in == nil {
		return nil
	}
	out := new(PatternAnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternConfig) DeepCopyInto(out *PatternConfig) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]ErrorPattern, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternConfig.
func (in *PatternConfig) DeepCopy() *PatternConfig {
	if in == nil {
		return nil
	}
	out := new(PatternConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternError) DeepCopyInto(out *PatternError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternError.
func (in *PatternError) DeepCopy() *PatternError {
	if in == nil {
		return nil
	}
	out := new(PatternError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCondition) DeepCopyInto(out *PodCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCondition.
func (in *PodCondition) DeepCopy() *PodCondition {
	if in == nil {
		return nil
	}
	out := new(PodCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSleuth) DeepCopyInto(out *PodSleuth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSleuth.
func (in *PodSleuth) DeepCopy() *PodSleuth {
	if in == nil {
		return nil
	}
	out := new(PodSleuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSleuth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSleuthList) DeepCopyInto(out *PodSleuthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodSleuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSleuthList.
func (in *PodSleuthList) DeepCopy() *PodSleuthList {
	if in == nil {
		return nil
	}
	out := new(PodSleuthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodSleuthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSleuthSpec) DeepCopyInto(out *PodSleuthSpec) {
	*out = *in
	if in.ReconcileInterval != nil {
		in, out := &in.ReconcileInterval, &out.ReconcileInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PodLabelSelector != nil {
		in, out := &in.PodLabelSelector, &out.PodLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.LogAnalysis != nil {
		in, out := &in.LogAnalysis, &out.LogAnalysis
		*out = new(LogAnalysisConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSleuthSpec.
func (in *PodSleuthSpec) DeepCopy() *PodSleuthSpec {
	if in == nil {
		return nil
	}
	out := new(PodSleuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSleuthStatus) DeepCopyInto(out *PodSleuthStatus) {
	*out = *in
	if in.NonReadyPods != nil {
		in, out := &in.NonReadyPods, &out.NonReadyPods
		*out = make([]NonReadyPodInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSleuthStatus.
func (in *PodSleuthStatus) DeepCopy() *PodSleuthStatus {
	if in == nil {
		return nil
	}
	out := new(PodSleuthStatus)
	in.DeepCopyInto(out)
	return out
}
